version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: dev-jungdam
    hostname: root
    restart: always
    ports:
      - "10001:3306"
    networks:
      - dev-jungdam
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jungdam
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - dev-jungdam:/var/lib/mysql

volumes:
  dev-jungdam:
    null
networks:
  dev-jungdam:
    driver: bridge
